#region License
// Copyright ©2017 Tacke Consulting (dba OpenNETCF)
//
// Permission is hereby granted, free of charge, to any person obtaining a copy of this software 
// and associated documentation files (the "Software"), to deal in the Software without restriction,
// including without limitation the rights to use, copy, modify, merge, publish, distribute, 
// sublicense, and/or sell copies of the Software, and to permit persons to whom the Software is 
// furnished to do so, subject to the following conditions:
//
// The above copyright notice and this permission notice shall be included in all copies or 
// substantial portions of the Software.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, 
// INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR 
// PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR 
// ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE,
// ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
//
#endregion
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OpenNETCF.Web {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("OpenNETCF.Web.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to bin.
        /// </summary>
        internal static string BinFolderName {
            get {
                return ResourceManager.GetString("BinFolderName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot redirect to new line.
        /// </summary>
        internal static string CannotRedirectToNewLine {
            get {
                return ResourceManager.GetString("CannotRedirectToNewLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Although the page seems to be valid, the server was unable to find its associated code-behind assembly.
        ///					&lt;ul style=&quot;list-style: square;&quot;&gt;
        ///						&lt;li style=&quot;padding-bottom: 5px;&quot;&gt;Check that the file mentioned in the exception exists on the device.&lt;/li&gt;
        ///						&lt;li style=&quot;padding-bottom: 5px; line-height: 1.4;&quot;&gt;Is the name of the assembly the same as the name specified in the ASP.NET page? They must be the same.&lt;/li&gt;
        ///					&lt;/ul&gt;.
        /// </summary>
        internal static string CodeBehindNotFoundDesc {
            get {
                return ResourceManager.GetString("CodeBehindNotFoundDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code-behind assembly, or one of its references, could not be found..
        /// </summary>
        internal static string CodeBehindNotFoundTitle {
            get {
                return ResourceManager.GetString("CodeBehindNotFoundTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;html style=&quot;background-color: #f0f0f0; font-family: Helvetica;  color: #000; font-size: 10.5pt; line-height: 1.4;&quot;&gt;
        ///	&lt;head&gt;
        ///		&lt;title&gt;Server Error: {0}&lt;/title&gt;
        ///	&lt;/head&gt;
        ///	&lt;body&gt;
        ///		&lt;center&gt;
        ///		&lt;div style=&quot;text-align: left; margin-top: 50px; margin-bottom: 0px; border: 1px solid #e3e3e3; width: 600px; background: #fff; margin-left: auto; margin-right: auto; 
        ///		padding-left: 10px; padding-right: 40px; padding-top: 30px; padding-bottom: 20px;&quot;&gt;		
        ///			&lt;div style=&quot;float: left; margin-left: 40px; width: 540px [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ContextualErrorTemplate {
            get {
                return ResourceManager.GetString("ContextualErrorTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A potentially dangerous {0} value was detected from the client ({1})..
        /// </summary>
        internal static string Dangerous_input_detected {
            get {
                return ResourceManager.GetString("Dangerous_input_detected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disk Error.
        /// </summary>
        internal static string DiskError {
            get {
                return ResourceManager.GetString("DiskError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A Disk/Drive Error has been occurred.  Check to ensure the Padarn Server is not out of disk space for temporary and log files..
        /// </summary>
        internal static string DiskErrorDesc {
            get {
                return ResourceManager.GetString("DiskErrorDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A Disk/Drive Error has occurred.
        /// </summary>
        internal static string DiskErrorTitle {
            get {
                return ResourceManager.GetString("DiskErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;html style=&quot;background-color: #f0f0f0; font-family: Helvetica;  color: #000; font-size: 11pt;&quot;&gt;
        ///	&lt;head&gt;
        ///		&lt;title&gt;Server Error: Unhandled exception in &apos;{0}&apos;&lt;/title&gt;
        ///	&lt;/head&gt;
        ///	&lt;body&gt;
        ///		&lt;center&gt;
        ///		&lt;div style=&quot;text-align: left; margin-top: 50px; margin-bottom: 0px; border: 1px solid #e3e3e3; width: 600px; background: #fff; margin-left: auto; margin-right: auto; 
        ///		padding-left: 10px; padding-right: 40px; padding-top: 40px; padding-bottom: 20px;&quot;&gt;		
        ///			&lt;div style=&quot;float: left; margin-left: 40px; width:  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ErrorPage {
            get {
                return ResourceManager.GetString("ErrorPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The page or file is missing and cannot be served.
        ///					&lt;ul style=&quot;list-style: square;&quot;&gt;
        ///						&lt;li style=&quot;padding-bottom: 5px;&quot;&gt;Check that the file mentioned in the exception exists on the device.&lt;/li&gt;
        ///							&lt;li style=&quot;padding-bottom: 5px;&quot;&gt;Check that the URL for the file is correct.&lt;/li&gt;
        ///					&lt;/ul&gt;.
        /// </summary>
        internal static string FileNotFoundDesc {
            get {
                return ResourceManager.GetString("FileNotFoundDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;html style=&quot;background-color: #f0f0f0; font-family: Helvetica;  color: #000; font-size: 10.5pt; line-height: 1.4;&quot;&gt;
        ///	&lt;head&gt;
        ///		&lt;title&gt;Server Error: Code-behind assembly not found.&lt;/title&gt;
        ///	&lt;/head&gt;
        ///	&lt;body&gt;
        ///		&lt;center&gt;
        ///		&lt;div style=&quot;text-align: left; margin-top: 50px; margin-bottom: 0px; border: 1px solid #e3e3e3; width: 600px; background: #fff; margin-left: auto; margin-right: auto; 
        ///		padding-left: 10px; padding-right: 40px; padding-top: 30px; padding-bottom: 20px;&quot;&gt;		
        ///			&lt;div style=&quot;float: left; mar [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string FileNotFoundErrorPage {
            get {
                return ResourceManager.GetString("FileNotFoundErrorPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The page or file cannot be found..
        /// </summary>
        internal static string FileNotFoundTitle {
            get {
                return ResourceManager.GetString("FileNotFoundTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accept-Ranges.
        /// </summary>
        internal static string HeaderAcceptRanges {
            get {
                return ResourceManager.GetString("HeaderAcceptRanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to bytes.
        /// </summary>
        internal static string HeaderAcceptRangesBytes {
            get {
                return ResourceManager.GetString("HeaderAcceptRangesBytes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Content-Length.
        /// </summary>
        internal static string HeaderContentLength {
            get {
                return ResourceManager.GetString("HeaderContentLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Content-Type.
        /// </summary>
        internal static string HeaderContentType {
            get {
                return ResourceManager.GetString("HeaderContentType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}: {1}\r\n.
        /// </summary>
        internal static string HeaderFormat {
            get {
                return ResourceManager.GetString("HeaderFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location.
        /// </summary>
        internal static string HeaderLocation {
            get {
                return ResourceManager.GetString("HeaderLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access is denied..
        /// </summary>
        internal static string HttpAccessDenied {
            get {
                return ResourceManager.GetString("HttpAccessDenied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access is forbidden..
        /// </summary>
        internal static string HttpAccessForbidden {
            get {
                return ResourceManager.GetString("HttpAccessForbidden", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HTTP/1.1 100 Continue\r\n.
        /// </summary>
        internal static string HttpContinue {
            get {
                return ResourceManager.GetString("HttpContinue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file enumerator has been denied access..
        /// </summary>
        internal static string HttpEnumeratorDenied {
            get {
                return ResourceManager.GetString("HttpEnumeratorDenied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred attempting to enumerate the files..
        /// </summary>
        internal static string HttpEnumeratorError {
            get {
                return ResourceManager.GetString("HttpEnumeratorError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error parsing request headers.
        /// </summary>
        internal static string HttpErrorParsingHeader {
            get {
                return ResourceManager.GetString("HttpErrorParsingHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file you are trying to access is hidden..
        /// </summary>
        internal static string HttpFileHidden {
            get {
                return ResourceManager.GetString("HttpFileHidden", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file you are trying to access cannot be found..
        /// </summary>
        internal static string HttpFileNotFound {
            get {
                return ResourceManager.GetString("HttpFileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HTTP/1.1 200 OK\r\n.
        /// </summary>
        internal static string HttpOK {
            get {
                return ResourceManager.GetString("HttpOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HTTP/1.1 400 Bad Request\r\n.
        /// </summary>
        internal static string HttpStatusBadRequest {
            get {
                return ResourceManager.GetString("HttpStatusBadRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HTTP/1.1 409 Conflict\r\n.
        /// </summary>
        internal static string HttpStatusConflict {
            get {
                return ResourceManager.GetString("HttpStatusConflict", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HTTP/1.1 417 ExpectationFailed\r\n.
        /// </summary>
        internal static string HttpStatusExpectationFailed {
            get {
                return ResourceManager.GetString("HttpStatusExpectationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HTTP/1.1 404 Not Found\r\n.
        /// </summary>
        internal static string HttpStatusFileNotFound {
            get {
                return ResourceManager.GetString("HttpStatusFileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HTTP/1.1 403 Forbidden\r\n.
        /// </summary>
        internal static string HttpStatusForbidden {
            get {
                return ResourceManager.GetString("HttpStatusForbidden", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HTTP/1.1 {0} Http Status\r\n.
        /// </summary>
        internal static string HttpStatusGeneric {
            get {
                return ResourceManager.GetString("HttpStatusGeneric", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HTTP/1.1 410 Gone\r\n.
        /// </summary>
        internal static string HttpStatusGone {
            get {
                return ResourceManager.GetString("HttpStatusGone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HTTP/1.1 500 Internal Server Error\r\n.
        /// </summary>
        internal static string HttpStatusInternalServerError {
            get {
                return ResourceManager.GetString("HttpStatusInternalServerError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HTTP/1.1 411 Length Required\r\n.
        /// </summary>
        internal static string HttpStatusLengthRequired {
            get {
                return ResourceManager.GetString("HttpStatusLengthRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HTTP/1.1 406 Not Acceptable\r\n.
        /// </summary>
        internal static string HttpStatusNotAcceptable {
            get {
                return ResourceManager.GetString("HttpStatusNotAcceptable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HTTP/1.1 405 Method Not Allowed\r\n.
        /// </summary>
        internal static string HttpStatusNotAllowed {
            get {
                return ResourceManager.GetString("HttpStatusNotAllowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HTTP/1.1 402 Payment Required\r\n.
        /// </summary>
        internal static string HttpStatusPaymentRequired {
            get {
                return ResourceManager.GetString("HttpStatusPaymentRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HTTP/1.1 412 Precondition Failed\r\n.
        /// </summary>
        internal static string HttpStatusPreconditionFailed {
            get {
                return ResourceManager.GetString("HttpStatusPreconditionFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HTTP/1.1 407 Proxy Authentication Required\r\n.
        /// </summary>
        internal static string HttpStatusProxyAuthRequired {
            get {
                return ResourceManager.GetString("HttpStatusProxyAuthRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HTTP/1.1 416 Requested Range Not Satisfiable\r\n.
        /// </summary>
        internal static string HttpStatusRequestedRangeNotSatisfiable {
            get {
                return ResourceManager.GetString("HttpStatusRequestedRangeNotSatisfiable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HTTP/1.1 413 Request Entity Too Large\r\n.
        /// </summary>
        internal static string HttpStatusRequestEntityTooLarge {
            get {
                return ResourceManager.GetString("HttpStatusRequestEntityTooLarge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HTTP/1.1 408 RequestTimeout\r\n.
        /// </summary>
        internal static string HttpStatusRequestTimeout {
            get {
                return ResourceManager.GetString("HttpStatusRequestTimeout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HTTP/1.1 414 Request URI Too Long\r\n.
        /// </summary>
        internal static string HttpStatusRequestURITooLong {
            get {
                return ResourceManager.GetString("HttpStatusRequestURITooLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HTTP/1.1 401 Unauthorized\r\n.
        /// </summary>
        internal static string HttpStatusUnauthorized {
            get {
                return ResourceManager.GetString("HttpStatusUnauthorized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HTTP/1.1 415 Unsupported Media Type\r\n.
        /// </summary>
        internal static string HttpStatusUnsupportedMediaType {
            get {
                return ResourceManager.GetString("HttpStatusUnsupportedMediaType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The HttpBrowserCapabilities string &apos;{1}&apos; evaluated to &apos;{2}&apos;.  {0}  Check the browserCaps section of machine.config or web.config to correct the error..
        /// </summary>
        internal static string Invalid_string_from_browser_caps {
            get {
                return ResourceManager.GetString("Invalid_string_from_browser_caps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The URL-encoded form data is not valid..
        /// </summary>
        internal static string Invalid_urlencoded_form_data {
            get {
                return ResourceManager.GetString("Invalid_urlencoded_form_data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid header encoding {0}..
        /// </summary>
        internal static string InvalidHeaderEncoding {
            get {
                return ResourceManager.GetString("InvalidHeaderEncoding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;configuration&gt;
        ///    &lt;configSections&gt;
        ///        &lt;section name=&quot;appSettings&quot; type=&quot;OpenNETCF.Configuration.NameValueFileSectionHandler, OpenNETCF.Configuration&quot; allowLocation=&quot;false&quot; /&gt;
        ///        &lt;section name=&quot;opennetcf.diagnostics&quot; type=&quot;OpenNETCF.Diagnostics.DiagnosticsConfigurationHandler, OpenNETCF&quot;/&gt;
        ///    &lt;/configSections&gt;
        ///&lt;/configuration&gt;.
        /// </summary>
        internal static string machine_config {
            get {
                return ResourceManager.GetString("machine_config", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum request length exceeded.
        /// </summary>
        internal static string Max_request_length_exceeded {
            get {
                return ResourceManager.GetString("Max_request_length_exceeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file being uploaded exceeds the maximum length allowed by the server configuration..
        /// </summary>
        internal static string MaxRequestLengthErrorDesc {
            get {
                return ResourceManager.GetString("MaxRequestLengthErrorDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload exceeds server setting.
        /// </summary>
        internal static string MaxRequestLengthErrorTitle {
            get {
                return ResourceManager.GetString("MaxRequestLengthErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No HTTP handler for this file type.
        /// </summary>
        internal static string NoHttpHandler {
            get {
                return ResourceManager.GetString("NoHttpHandler", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Out of disk space.
        /// </summary>
        internal static string OutOfDiskSpaceError {
            get {
                return ResourceManager.GetString("OutOfDiskSpaceError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The HTTP request has resulted in an out of memory exception. Please ensure the requestLengthDiskThreshold configuration setting does not exceed the amount of available memory..
        /// </summary>
        internal static string OutOfMemoryErrorDesc {
            get {
                return ResourceManager.GetString("OutOfMemoryErrorDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The server has no available memory.
        /// </summary>
        internal static string OutOfMemoryErrorTitle {
            get {
                return ResourceManager.GetString("OutOfMemoryErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Out of memory.
        /// </summary>
        internal static string OutOfMemoryException {
            get {
                return ResourceManager.GetString("OutOfMemoryException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page_Load.
        /// </summary>
        internal static string PageLoadEventName {
            get {
                return ResourceManager.GetString("PageLoadEventName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The code-behind class for this page is either missing from the assembly or is invalid.
        ///					&lt;ul style=&quot;list-style: square;&quot;&gt;
        ///						&lt;li style=&quot;padding-bottom: 5px;&quot;&gt;Check that the code-behind class derives from &lt;b&gt;OpenNETCF.Web.UI.Page&lt;/b&gt;.&lt;/li&gt;
        ///						&lt;li style=&quot;padding-bottom: 5px;&quot;&gt;Is the name of the code-behind class the same as the name specified in the ASP.NET page? They must be the same.&lt;/li&gt;
        ///						
        ///						&lt;li style=&quot;padding-bottom: 5px;&quot;&gt;Check the scope of the code-behind class and make sure it is [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TypeLoadDesc {
            get {
                return ResourceManager.GetString("TypeLoadDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing or invalid page class.
        /// </summary>
        internal static string TypeLoadTitle {
            get {
                return ResourceManager.GetString("TypeLoadTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You do not have permission to view this directory or page using the credentials you supplied..
        /// </summary>
        internal static string UnauthorizedDesc {
            get {
                return ResourceManager.GetString("UnauthorizedDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logon failed due to server configuration.
        /// </summary>
        internal static string UnauthorizedTitle {
            get {
                return ResourceManager.GetString("UnauthorizedTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was an unhandled exception in &apos;{0}&apos;. Please review the exception and stack trace below. .
        /// </summary>
        internal static string UnhandledExceptionDesc {
            get {
                return ResourceManager.GetString("UnhandledExceptionDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unsupported method in query: {0}.
        /// </summary>
        internal static string UnsupportedMethod {
            get {
                return ResourceManager.GetString("UnsupportedMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are not authorized to view this page.
        /// </summary>
        internal static string UnuthorizedMessage {
            get {
                return ResourceManager.GetString("UnuthorizedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} attribute not found in the VirtualDirectory node in {1}..
        /// </summary>
        internal static string VirtualDir_AttributeNotFound {
            get {
                return ResourceManager.GetString("VirtualDir_AttributeNotFound", resourceCulture);
            }
        }
    }
}
