//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3082
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SampleSite.Providers {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    internal class BeerSvcResrc {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        internal BeerSvcResrc() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SampleSite.Providers.BeerSvcResrc", typeof(BeerSvcResrc).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE HTML PUBLIC &quot;-//W3C//DTD HTML 4.0 Transitional//EN&quot;&gt;&lt;HTML&gt;&lt;HEAD&gt;&lt;TITLE&gt;OpenNETCF Padarn Web Server&lt;/TITLE&gt;
        ///&lt;LINK REL=&quot;stylesheet&quot; TYPE=&quot;text/css&quot; HREF=&quot;/css/SampleSite.css&quot; MEDIA=&quot;screen&quot; /&gt;&lt;/HEAD&gt;
        ///&lt;BODY&gt;&lt;DIV ID=&quot;container&quot;&gt;&lt;DIV ID=&quot;header&quot;&gt;&lt;DIV CLASS=&quot;src-links&quot;&gt;&amp;nbsp;&amp;nbsp;View source:&amp;nbsp;&lt;A HREF=&quot;/docs/Default_ASPX.htm&quot;&gt;ASPX&lt;/A&gt;&amp;nbsp;/&amp;nbsp;&lt;A HREF=&quot;/docs/Default_CS.htm&quot;&gt;Code-behind&lt;/A&gt;&lt;/DIV&gt;
        ///&lt;IMG SRC=&quot;/images/header.png&quot; ALT=&quot;Padarn Web Server&quot;&gt;&lt;/DIV&gt;
        ///&lt;br&gt;
        ///
        ///&lt;div&gt;
        ///&lt;h3&gt;Beer Database Ser [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string HTML_TEMPLATE {
            get {
                return ResourceManager.GetString("HTML_TEMPLATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;Beer&gt;
        ///		&lt;Name&gt;{0}&lt;/Name&gt;
        ///		&lt;Brewery&gt;{1}&lt;/Brewery&gt;
        ///		&lt;IsLager&gt;{2}&lt;/IsLager&gt;
        ///	&lt;/Beer&gt;.
        /// </summary>
        internal static string XML_ITEM_TEMPLATE {
            get {
                return ResourceManager.GetString("XML_ITEM_TEMPLATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot;?&gt;
        ///&lt;Beers&gt;
        ///	{0}
        ///&lt;/Beers&gt;.
        /// </summary>
        internal static string XML_TEMPLATE {
            get {
                return ResourceManager.GetString("XML_TEMPLATE", resourceCulture);
            }
        }
    }
}
